CLUSTAL multiple sequence alignment by MUSCLE (3.8)


sp|Q4VBE4|EGFLA_MOUSE      MDLISTFSLHFLLLACSLPPGAVSLRTALRKSGKVGPPLD-IKLGALNCTAFSIQWKTPK
sp|B4F785|EGFLA_RAT        MDLISTFLLHFLLLACSLPPGAVSLRTALRKSGKVGPPLD-IKLGALNCTAFSIQWKTPK
NP_689616.2                MDLIRGVLLRLLLLASSLGPGAVSLRAAIRKPGKVGPPLD-IKLGALNCTAFSIQWKMPR
sp|A3KN33|EGFLA_BOVIN      MDLIRGVLLRLLLLASSLGPGAAPLRSALRKQGKVGPPLD-IILDALNCSAFSIQWKMPR
A.                         -----------MTIEVNFRPDAADGLILYAARSGSTPSSDFIALGMYD------------
XP_027866151.1             -------------IKINFRPDNVDGMILYNGQRRTTGA-DFISLGLVS------------
A.                         -------------IKINFRPDNVDGMILYNGQRRTTGA-DFISLGLVS------------
                                        :  .: *. .              . * * *.  .            

sp|Q4VBE4|EGFLA_MOUSE      RSGSSIIGYTVFYSEVGSDKSLRERSHNVPVGQDTLIT---------EEVIGDLKPGTEY
sp|B4F785|EGFLA_RAT        RSGSSIVGYTVFYSELGSDKSLREQSHNVPVGQDTLIT---------EEVIGDLKPGTEY
NP_689616.2                HPGSPILGYTVFYSEVGADKSLQEQLHSVPLSRDIPTT---------EEVIGDLKPGTEY
sp|A3KN33|EGFLA_BOVIN      HPPSPIMGYTVFYSEVGIDKSLQERSYGVPPGLDTPTSGRLDHQMIFEEVIGDLKPGTEY
A.                         -------GFVEFRYNLGGLTAEIKSAARVTLGETHTVT-----------ATRELRNGFLT
XP_027866151.1             -------GRLEFRFDVGSGMATIRDPHPIKLGEFHTVE-----------LYRNLTQGYIT
A.                         -------GRLEFRFDVGSGMATIRDPNPIKLGEFHTVE-----------VYRNLTQGYIT
                                  *   *  ::*   :       :  .                    :*  *   

sp|Q4VBE4|EGFLA_MOUSE      QVSVAAYSQTGKGRLSFPRHVTTLSQDSCLPPAAPQQPHVLVVSDSEVALSWRPGENEGS
sp|B4F785|EGFLA_RAT        RVSIAAYSQTGKGRLSFPRHVTTLSQDSCLPPEAPHQPHVLVVSDSEVALSWRPGENEGS
NP_689616.2                RVSIAAYSQAGKGRLSSPRHVTTLSQDSCLPPAAPQQPHVIVVSDSEVALSWKPGASEGS
sp|A3KN33|EGFLA_BOVIN      RVSMAAYSQTGKGRLSSPQHVTTLPQDSCLPPTAPQQPHVIVVSDSEVALSWKPGESEGS
A.                         VDGLDVVLGTSGGS----------------------------VTRLDVNLEVFVGGHDD-
XP_027866151.1             VDGGEPISGKSQGK----------------------------FQGLDLNEELHVGGYPN-
A.                         VDGGEPISGKSQGK----------------------------FQGLDLNEELHVGGYPN-
                             .       . *                             .   ::  .   *   . 

sp|Q4VBE4|EGFLA_MOUSE      APIQSYSVEFIRPDFDKSWTIIQERLQMDS--MVIKGLDPDT------NYQF--AVKAMN
sp|B4F785|EGFLA_RAT        APIQSYSVEFIRPDFDKSWTIIQERLQMDS--MVIKGLDPDT------NYQF--AVRAMN
NP_689616.2                APIQYYSVEFIRPDFDKKWTSIHERIQMDS--MVIKGLDPDT------NYQF--AVRAMN
sp|A3KN33|EGFLA_BOVIN      SPIQYYSVEFTRPDFDKSWTSIREQIQMDS--MVIKGLDPDT------NYQF--AVRAVN
A.                         -----FTQVLAGAGFTSSFTGCIFSLLVNG--LSFHDVGRSNRGVGVSECDVHPCDELSC
XP_027866151.1             -----YTSIVKTAGIKTGFVGCIRQLVIQGEEVIFKELDRSS--TGVTNCPT--CKDYPC
A.                         -----YTSIVKTAGIKTGFVGCIRQLVIQGEEVIFKELDRSS--TGVTNCPT--CIDYPC
                                ::  .  ..: . :.     : ::.  : :: :. ..      :     .     

sp|Q4VBE4|EGFLA_MOUSE      AHGFSPRSWPSNTVRTLGPG----------------------------------------
sp|B4F785|EGFLA_RAT        AYGFSLRSQPSNTIRTLGPG----------------------------------------
NP_689616.2                SHGPSPRSWPSDIIRTLCPEEAGSGRYGPRYITDMGAGEDDEGFEDDLDLDISFEEVKPL
sp|A3KN33|EGFLA_BOVIN      PHGSSPRSQPS-------------------------------------------------
A.                         QNGGTCTNT-TGVFECVCTSEFNGTQCERPI-----------------------------
XP_027866151.1             QNGGTCKDSEASLYRCTCPRGFTGSNCQ--------------------------------
A.                         QNGGTCKDSEASLYRCTCPRGFTGSNCQ--------------------------------
                             * :  .  :                                                 
