---
title: "Class 07 Packages"
author: "Draymond Green"
date: "10/22/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R function

```{r}
source("http://tinyurl.com/rescale-R")
```


```{r}
rescale(1:10)
```


```{r}
rescale(c(1,10,5,NA,6))
```

```{r}
rescale2(c(1:10, "Why_is_gamora"))
```


Write function to find where NA is in two input vectors
write simple input where know answer
```{r}
x <- c( 1, 2, NA, 3, NA)
y <- c(NA, 3, NA, 3, 4)
```
found **is.na()** function
```{r}
is.na(x)
```
**which**
```{r}
which(is.na(x))
```

```{r}
which( is.na(y))
```


```{r}
is.na(x)
is.na(y)
```

```{r}
is.na(x) & is.na(y)
```

sum(is.na(x) & is.na(y))
**sum()** tell you how much TRUE you have
```{r}
sum( !c(TRUE, TRUE, FALSE, TRUE))
```

now turn into function

na_na <- function(x, y) {
  sum(is.na(x) & is.na(y))
}
both_na()
```{r}
na_na <- function(x, y) {
  sum(is.na(x) & is.na(y))
}
```

```{r}
na_na(x,y)
```

x <- c(NA, NA, NA)
y1 <- c( 1, NA, NA)
y2 <- c( 1, NA, NA, NA)
```{r}
x <- c(NA, NA, NA)
y1 <- c( 1, NA, NA)
y2 <- c( 1, NA, NA, NA)
```
```{r}
both_na(x, y2)
```

```{r}
x2 <- c(NA, NA)
both_na(x2, y2)
```
Recycle 
```{r}
plot(1:10, col=c("red", "salmon", "magenta"))
```

```{r}
x <- c(1, NA, NA)
y3 <- c( 1, NA, NA, NA, NA, NA, NA)
both_na(x, y3)
```

```{r}
length(x)
length(y3)
```


```{r}
na_na2 <- function(x, y) {
  if(length(x) != length(y)) {
    stop("must be same on gau zai")
  }
  sum(is.na(x) & is.na(y))
}
```

"mayonaise" == "instrument"

```{r}
na_na2(x, y3)
```


```{r}
student_1 <- c(100, 100, 100, 100, 100, 100, 100, 90)
student_2 <- c(100, NA, 90, 90, 90, 97, 80)

student_1[-which.min(student_1)]
mean(student_1[-which.min(student_1)])
```

```{r}
student_2[-which.min(student_2)]
mean(student_2[-which.min(student_2)])
```

```{r}
student_2[-which.min(student_2)]
mean(student_2[-which.min(student_2)], na.rm = TRUE)
```

```{r}
grade <- function(x) {
  if(any(is.na(x))){
    warning("Stupid")
  }
  mean(x[-which.min(x)], na.rm = TRUE)
}
```

```{r}
grade(student_1)
grade(student_2)
```

```{r}
url <- "https://tinyurl.com/gradeinput"
hw <- read.csv(url, row.names=1)
```

```{r}
apply(hw, 1, grade)
```

